build:
	# gcc -o test_stack.out test_stack.c;./test_stack.out;
	# gcc -o test_string_operations.out test_string_operations.c;./test_string_operations.out;
	rm test_parser_graph.out;gcc -o test_parser_graph.out test_parser_graph.c;./test_parser_graph.out;
	# rm test_dictionary.out; gcc -o test_dictionary.out test_dictionary.c; ./test_dictionary.out
	# rm test_expr.out; gcc -o test_expr.out test_expr.c; ./test_expr.out
	# rm test_stack_operations.out;gcc -o test_stack_operations.out test_stack_operations.c;./test_stack_operations.out;
